name: Docker Manifest GitHub Action
description: 🐳 GitHub action to apply Docker manifest objects onto an image.
author: Noelware <team@noelware.org>

branding:
  icon: box
  color: blue

runs:
  using: node16
  main: ./build/index.js

inputs:
  base-image:
    description:
      The name:tag of the final image containing all extra-images. Optionally, comma-separate to create multiple final images with the same
      manifest.
    required: true

  extra-images:
    description: A comma-separated list of extra images to apply to the base-image input.
    required: true

  push:
    description: Pushes the base-image to the registry it belongs to.
    required: false
    default: 'true'

  amend:
    description: If the manifest command should override tags
    required: false
    default: 'false'
